#!/usr/bin/env python3
"""
Weekly auto-research runner — discovers frontier topics from interest history
and runs the full headless pipeline on each, then writes a digest report.

Cron schedule: 0 12 * * 3  (Wednesdays at noon)

    python -m reddit_research.auto_research
    python -m reddit_research.auto_research --dry-run   # predict only, no fetch
    python -m reddit_research.auto_research --limit 2   # override MAX_PREDICTIONS_PER_RUN
"""
from __future__ import annotations

from reddit_research.utils.env_loader import load_env
from reddit_research.utils.logging_config import configure_logging

load_env()
configure_logging()

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

from reddit_research import db, predictor
from reddit_research.predictor import MAX_PREDICTIONS_PER_RUN
from reddit_research.researcher import auto_subreddits
from reddit_research.utils.logging_config import get_logger

log = get_logger(__name__)


def _log(msg: str) -> None:
    print(f"[AUTO] {msg}", flush=True)


def _run_research(query: str, limit: int) -> Path | None:
    """Run the headless pipeline for one query. Returns report path or None on failure."""
    from reddit_research import headless
    try:
        subreddits = auto_subreddits(query, llm_fallback=True)
        _log(f"Researching: {query!r} → subreddits: {', '.join(subreddits)}")
        path = headless.run(query, subreddits)

        # Bump the research count for the new topic so future scoring sees it
        topic = next(
            (t for t in db.get_all_topics_with_signals() if t["name"] == query),
            None,
        )
        if topic:
            db.increment_topic_researched(topic["id"])

        return path
    except Exception:
        log.exception("auto_research: headless run failed for %r", query)
        return None


def _write_digest(researched: list[dict], dry_run: bool) -> Path:
    """Write a weekly digest markdown summarising what was auto-researched."""
    from reddit_research.report import REPORTS_DIR

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc)
    filename = f"auto_digest_{now.strftime('%Y-%m-%d')}.md"
    path = REPORTS_DIR / filename

    lines = [
        f"# Auto-Research Digest — {now.strftime('%A %d %B %Y')}",
        "",
        "> Generated by the Wednesday noon cron job.",
        "",
    ]

    if dry_run:
        lines += ["**Dry-run mode — no research was actually performed.**", ""]

    if not researched:
        lines += ["No predictions were generated this cycle.", ""]
    else:
        lines += [
            f"## Topics researched this cycle ({len(researched)})",
            "",
        ]
        for item in researched:
            status = item.get("status", "ok")
            score = item.get("predicted_score", 0)
            report = item.get("report_path")
            lines.append(f"### {item['query']}")
            lines.append(f"- Predicted relevance score: **{score:.3f}**")
            lines.append(f"- Status: {status}")
            if report:
                lines.append(f"- Report: `{report}`")
            lines.append("")

    top_topics = predictor.get_interest_ranked_topics(limit=5)
    if top_topics:
        lines += ["## Your top interest areas", ""]
        for t in top_topics:
            lines.append(
                f"- **{t['name']}** "
                f"(researched {t.get('times_researched', 1)}×, "
                f"interest score: {t.get('_interest_score', 0):.2f})"
            )
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def main():
    parser = argparse.ArgumentParser(description="Auto-research weekly cron runner")
    parser.add_argument("--dry-run", action="store_true", help="Predict topics but skip fetching")
    parser.add_argument("--limit", type=int, default=MAX_PREDICTIONS_PER_RUN, help="Max topics to research")
    args = parser.parse_args()

    db.init_db()
    _log("Starting auto-research cycle...")

    # Step 1: pull any pending predictions from a previous cycle, or generate fresh ones
    pending = db.get_pending_predictions(limit=args.limit)
    if not pending:
        _log("No pending predictions — running prediction cycle...")
        predictor.run_prediction_cycle()
        pending = db.get_pending_predictions(limit=args.limit)

    if not pending:
        _log("No predictions generated — not enough research history yet. Run some manual topics first.")
        _write_digest([], dry_run=args.dry_run)
        sys.exit(0)

    _log(f"Predictions to research: {[p['query'] for p in pending]}")

    # Step 2: research each predicted topic
    results: list[dict] = []
    for pred in pending[: args.limit]:
        item: dict = {
            "query": pred["query"],
            "predicted_score": pred["predicted_score"],
        }

        if args.dry_run:
            _log(f"[dry-run] Would research: {pred['query']!r}")
            item["status"] = "dry-run"
        else:
            report_path = _run_research(pred["query"], args.limit)
            if report_path:
                db.mark_prediction_researched(pred["id"])
                item["status"] = "ok"
                item["report_path"] = str(report_path)
                _log(f"Done: {pred['query']!r} → {report_path.name}")
            else:
                item["status"] = "error"
                _log(f"Failed: {pred['query']!r}")

        results.append(item)

    # Step 3: write digest
    digest = _write_digest(results, dry_run=args.dry_run)
    _log(f"Digest written: {digest}")

    # Step 4: refresh predictions for next Wednesday
    if not args.dry_run:
        _log("Refreshing predictions for next cycle...")
        predictor.run_prediction_cycle()

    _log("Auto-research cycle complete.")


if __name__ == "__main__":
    main()
